osas/osas/composeexample/composeexample/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

osas/osas/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name="home"),
    path('process/', views.process, name="process"),
    path('list/', views.list, name="list"),
]

osas/osas/osas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if settings.DEBUG:
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

osas/osas/main/models.py
from django.db import models

# Create your models here.


class Sinav(models.Model):
    bolum = models.CharField(max_length=200)
    ders = models.CharField(max_length=200)
    sinav_tipi = models.CharField(max_length=200)
    tc = models.BigIntegerField(primary_key=True, max_length=11)
    kagit = models.ImageField(blank=True, null=True)

    class Meta:
        unique_together = (('ders', 'sinav_tipi', 'tc'))

osas/osas/main/forms.py
from django import forms


class UploadForm(forms.Form):
    img = forms.ImageField(label="Choose your image")

osas/osas/main/views.py
from django.shortcuts import render
import cv2 as cv
from . import final2
from . import utils
from . import forms, models
from django.core.files.storage import FileSystemStorage
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.exceptions import ObjectDoesNotExist
# InMemoryUploadedFile.
# from django.urls import reverse
# Create your views here.


def home(request):

    return render(request, 'home.html', {
        'form':  forms.UploadForm()
    })


def process(request):

    filelist = request.FILES.getlist('img')

    qrList = []
    tcList = []

    height = 1200
    width = 900
    for f in filelist:
        fs = FileSystemStorage()
        name = fs.save(f.name, f)
        img = cv.imread('./media/'+f.name)
        tc = final2.get_tc(img)
        qr_code = final2.get_qrcode(
            img[0:height//4, 0:width//2])

        qr_code_sonuc = str(qr_code).split("\n")
        print("the length of qr code ", len(qr_code_sonuc))

        if len(qr_code_sonuc) == 3:

            bolum = qr_code_sonuc[0]
            ders = qr_code_sonuc[1]
            sinav_tipi = qr_code_sonuc[2]
        else:
            qr_code_sonuc = str(qr_code)
            bolum = "QR kod Hatasi"
            ders = "QR kod Hatasi"
            sinav_tipi = "QR kod Hatasi"

        kagit = f.name
        print(tc)
        print(name, 'file name')
        # Algılanan qr kod ve tc değerleri veritabanı eklenecektir
        exists = False
        red = 0
        if len(tc) == 11:
            try:
                n = models.Sinav.objects.get(tc=tc)
                exists = True
            except ObjectDoesNotExist:
                exists = False

            if not exists:

                models.Sinav.objects.create(
                    tc=tc, bolum=bolum, ders=ders, sinav_tipi=sinav_tipi, kagit=kagit)
            else:
                fs.delete(name)

        else:
            fs.delete(name)
            red = 1

        tup = (tc, qr_code)
        tcList.append(tup)

    # models.Sinav.objects.all().delete()
    print("objects len", len(models.Sinav.objects.all()))

    tc = 2
    qr_code = 2

    return render(request, 'home.html', {
        'form':  forms.UploadForm(),
        'tc': tcList,
        'red': red
        # 'qr_code': qrList
    })


def list(request):
    print(type(models.Sinav.objects.all()))
    return render(request, 'home.html', {
        'sinavList':  models.Sinav.objects.all()
    })

osas/osas/main/templates/home.html
{% load static%}
{% load type_template_tags%}
<!DOCTYPE html>
<!-- saved from url=(0022)http://127.0.0.1:8000/ -->
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>OMU Sınav Arşivleme Sistemi</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/all.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/style2.css'%}">
    <link rel="stylesheet" href="{% static 'main/fontawesome-free-5.15.2-web/css/all.css' %}">
    <style type="text/css">

    </style>
</head>

<body>
    <nav class="u-clearfix">
        <div class="logo pt-2">
            <a href="/" rel="noopener">
                <h2>OMU Sınav Arşivleme Sistemi </h2>
            </a>
        </div>
        <div class="release-notes">
            <p style="font-size: 20px;font-weight: 700;text-decoration: none;"> <a href="{% url 'main:list' %}"
                    target="" rel="noopener">System
                    Database
                </a> </p>
        </div>
    </nav>
    <main class=" container-fluid row">
        {% if not tc and not sinavList%}
        <div class="col blink_me">
            <div class="shadow2">
                <img class="sinav-ornek" src="/media/SinavOrnegi.png">
            </div>

        </div>
        {%endif%}
        <div class=" col w-50 text-center mx-auto pt-5">

            {% if tc %}

            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">T.C. Identity No <br>From the Optic Form</th>
                        <th scope="col">Exam information <br> From the QR code</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x,y in tc%}
                    <tr>

                        <th scope="row">{{forloop.counter}}</th>
                        {% if x|length != 11 %}
                        <td style="color: red;">
                            {{x}} </td>
                        {% else%}

                        <td style="color: rgb(60, 113, 192);"> {{x}}</td>
                        {%endif%}
                        <td>{{y}}</td>
                    </tr>

                    {%endfor%}

                </tbody>
            </table>
            {%elif sinavList%}
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">T.C.</th>
                        <th scope="col">Department</th>
                        <th scope="col">Class</th>
                        <th scope="col">Exam Type</th>
                        <th scope="col">Exam Paper</th>
                    </tr>
                </thead>
                <tbody>
                    {% for x in sinavList%}

                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        {% if x.tc %}
                        <td>
                            {{x.tc}}
                        </td>
                        {%endif%}
                        <td>{{x.bolum}}</td>
                        <td>{{x.ders}}</td>
                        <td>{{x.sinav_tipi}}</td>
                        <td>{{x.kagit.url}}<a href="{{x.kagit.url}}"><i class="fa fa-image"></i></a></td>
                    </tr>



                    {%endfor%}
                </tbody>
            </table>
            {%else%}
            <form action="/process/" method="POST" enctype="multipart/form-data">
                {% csrf_token%}
                <div class="upload_button"><i class="fa fa-upload upload_i"></i></div>

                <input type="file" name="img" accept="image/*" multiple>
                <!-- {{form}} -->
                <input type="submit" value="Upload Exams">
                <h2 class="num"></h2>
            </form>
            {% endif%}
            {% if qr_code %}
            <h2>Cikarilan qr_code bilgileri: {{qr_code}}</h2>
            {% endif%}
        </div>

    </main>
    <footer class="u-clearfix text-center ">
        <!-- <a href="https://docs.djangoproject.com/en/3.1/" target="_blank" rel="noopener">
            <div class="option one">
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <defs>
                        <path d="M0 0h24v24H0V0z" id="a"></path>
                    </defs>
                    <clippath id="b">
                        <use overflow="visible" xlink:href="#a"></use>
                    </clippath>
                    <path clip-path="url(#b)"
                        d="M9 21c0 .55.45 1 1 1h4c.55 0 1-.45 1-1v-1H9v1zm3-19C8.14 2 5 5.14 5 9c0 2.38 1.19 4.47 3 5.74V17c0 .55.45 1 1 1h6c.55 0 1-.45 1-1v-2.26c1.81-1.27 3-3.36 3-5.74 0-3.86-3.14-7-7-7zm2.85 11.1l-.85.6V16h-4v-2.3l-.85-.6C7.8 12.16 7 10.63 7 9c0-2.76 2.24-5 5-5s5 2.24 5 5c0 1.63-.8 3.16-2.15 4.1z">
                    </path>
                </svg>
                <div>
                    <h4>Django Documentation</h4>
                    <p>Topics, references, &amp; how-to’s</p>
                </div>
            </div>
        </a> -->
        <!-- <a target="_blank" rel="noopener">
            <div class="option two">
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 0h24v24H0V0z" fill="none"></path>
                    <path
                        d="M9.4 16.6L4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4zm5.2 0l4.6-4.6-4.6-4.6L16 6l6 6-6 6-1.4-1.4z">
                    </path>
                </svg>
                <div>
                    <h4>Front-End: Ammar RAHMOUNI</h4>
        </div>
        </div>
        </a> -->
        <a href="https://github.com/ggnucky" target="_blank" rel="noopener">
            <div class="option two">

                <div>
                    <h4>Tarık Kaiatoğlu</h4>
                    <!-- <p>Get started with Django</p> -->
                </div>
            </div>
        </a>
        <a href="https://github.com/457341" target="_blank" rel="noopener">
            <div class="option two">

                <div>
                    <h4>Manzoor Hussain</h4>
                    <!-- <p>Get started with Django</p> -->
                </div>
            </div>
        </a>
        <a href="https://github.com/ammarrahmouni" target="_blank" rel="noopener">
            <div class="option two">

                <div>
                    <h4>Ammar Rahmouni</h4>
                    <!-- <p>Get started with Django</p> -->
                </div>
            </div>
        </a>
        <a href="https://github.com/zaidasim232" target="_blank" rel="noopener">
            <div class="option two">

                <div>
                    <h4>Zaid Ahmed</h4>
                    <!-- <p>Get started with Django</p> -->
                </div>
            </div>
        </a>
        <!-- <a href="https://www.djangoproject.com/community/" target="_blank" rel="noopener">
            <div class="option three">
                <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M0 0h24v24H0z" fill="none"></path>
                    <path
                        d="M16.5 13c-1.2 0-3.07.34-4.5 1-1.43-.67-3.3-1-4.5-1C5.33 13 1 14.08 1 16.25V19h22v-2.75c0-2.17-4.33-3.25-6.5-3.25zm-4 4.5h-10v-1.25c0-.54 2.56-1.75 5-1.75s5 1.21 5 1.75v1.25zm9 0H14v-1.25c0-.46-.2-.86-.52-1.22.88-.3 1.96-.53 3.02-.53 2.44 0 5 1.21 5 1.75v1.25zM7.5 12c1.93 0 3.5-1.57 3.5-3.5S9.43 5 7.5 5 4 6.57 4 8.5 5.57 12 7.5 12zm0-5.5c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2zm9 5.5c1.93 0 3.5-1.57 3.5-3.5S18.43 5 16.5 5 13 6.57 13 8.5s1.57 3.5 3.5 3.5zm0-5.5c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2z">
                    </path>
                </svg>
                <div>
                    <h4>Django Community</h4>
                    <p>Connect, get help, or contribute</p>
                </div>
            </div>
        </a> -->
    </footer>
    <script type="text/javascript" src="{% static 'main/js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'main/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'main/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script>
        $(function () {
            console.log('done')
            // console.log($("input[type='file']").target)
            // if ($("input[type='file']").val() == "") {

            // } else {

            // }
            $("input[type='file']").change(function (e) {
                console.log(typeof $(this).val());
                console.log(e.target.files.length);
                var length = e.target.files.length;
                $('.num').text(length + " File/s")
            })
        });
    </script>
</body>

</html>